### ISSUE TITLE
Importing Barbara issue

### ISSUE THREAD

**Issue by awaiting-death** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#22]
![1](https://user-images.githubusercontent.com/29349728/204556607-aceb8239-8f83-492e-bb00-88a940d49490.png)

Hi, when importing Barbara, if I click 'Import Outline Lightmaps' this error makes happen.
Aany help would be appreciated. Thanks.

**Comment by michael-gh1** [comment]
Hi @awaiting-death, it seems like Barbara has no `Face` material in her model which causes this.

What you can do is create a new material named `Mat_Face` and then assign it to the `Brow`, `Face` and `Face_Eye` meshes.

Instead of clicking the simplified `Run Entire Setup` button, you'll need to run the steps under the `Basic Setup` instead.

1. Under `Basic Setup` click `Set Up Character`
  a. Select Character Folder
3. Create a new material named `Mat_Face` (ex. select `Face`, create a new material and then rename it)
4. Assign this material to the `Brow`, `Face` and `Face_Eye` meshes
5. Continue with the `Basic Setup` steps
  a. `Set Up Materials`
  b. `Set Up Outlines`
  c. `Finish Setup` 

Let me know if this works for you and if you need any further assistance!

<br>
Example Screenshot of Step 2:

![image](https://user-images.githubusercontent.com/8632035/204637921-6c657319-5d76-45b6-9851-454d04e48b01.png)

**Comment by awaiting-death** [comment]
> 

Thank you so much! It works perfectly now.

**Comment by michael-gh1** [comment]
Awesome! Glad to hear that!
